# Generated by Django 3.1.3 on 2020-12-03 15:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=999999)),
                ('cep', models.CharField(blank=True, max_length=999999, null=True)),
                ('address', models.CharField(blank=True, max_length=999999, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=999999, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=999999, null=True)),
                ('annual_gross', models.BigIntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField()),
                ('city_name', models.CharField(blank=True, max_length=999999, null=True)),
                ('state_code', models.CharField(blank=True, max_length=999999, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=999999, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('address_compliment', models.CharField(blank=True, max_length=999999, null=True)),
                ('annual_gross_2019', models.BigIntegerField(blank=True, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
                ('cnae', models.TextField(blank=True, null=True)),
                ('confirmed_annual_revenue', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=999999)),
                ('last_name', models.CharField(max_length=999999)),
                ('legal_name', models.CharField(blank=True, max_length=999999, null=True)),
                ('email', models.CharField(max_length=999999, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=999999, null=True)),
                ('cpf', models.CharField(blank=True, max_length=999999, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('company_role', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=999999, null=True)),
                ('address_compliment', models.CharField(blank=True, max_length=999999, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=999999, null=True)),
                ('city_name', models.CharField(blank=True, max_length=999999, null=True)),
                ('state_code', models.CharField(blank=True, max_length=999999, null=True)),
                ('cep', models.CharField(blank=True, max_length=999999, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finove_data_service.company')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('status', models.TextField()),
                ('details_code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finove_data_service.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finove_data_service.user')),
            ],
            options={
                'db_table': 'verification',
            },
        ),
        migrations.CreateModel(
            name='ResponseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=999999)),
                ('source_url', models.CharField(max_length=999999)),
                ('data', models.JSONField()),
                ('cnpj', models.CharField(max_length=999999, null=True)),
                ('last_update', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finove_data_service.verification')),
            ],
            options={
                'db_table': 'response_record',
            },
        ),
    ]
